
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${USERNAME:root}
    password: ${PASSWORD:root}
    url: jdbc:mysql://47.104.201.221:3306/mall?characterEncoding=utf-8&useSSL=false
server:
  port: 9001
logging:
  pattern:
    console: "[thread] %-5level %logger{36} - %msg%n"